/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://xdlo4oa7kjbufgtnczmdhzmdma.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-luiopcy65nde3cf5eqflqwlhvy",
    "aws_cognito_identity_pool_id": "us-east-1:41c2966b-f5d4-494c-b9fb-2f115309a7f3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_85iAHQaeM",
    "aws_user_pools_web_client_id": "5uj4h9d739jpl4v53hidtr5f80",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "productimages3bucketba67c-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
