/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://s5hcybgqxzhmhmngzdhurfmszu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-n7rcjolbifdb5omipjuyu4jcce",
    "aws_cognito_identity_pool_id": "us-east-1:09b7ce9a-6cb8-4625-8b3f-01faf1278578",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_j9Eg4REpA",
    "aws_user_pools_web_client_id": "6l0f6qd11kremgpktiakpmqvo1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "productimages3bucket7f1c1-migrate",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
