/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://skzwtclsircsjeian43ekmlnxy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "da2-3b4yvell4vawtgyoud3iofljna",
    "aws_cognito_identity_pool_id": "us-east-1:8aded824-d265-4809-937b-53236ee7bd72",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_B8NtLkXyd",
    "aws_user_pools_web_client_id": "6ariqq2o6nljeotcp4rivj4mjh",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "productimages3bucketbb5de-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
